print(solution("...!@BaT#*..y.abcdefghijklm"))
print(solution("z-+.^."	))
print(solution("=.="))
print(solution("123_.def"))
print(solution("abcdefghijklmn.p"))
print(solution("./././././abcd/././././."))